-- 1. List all customers who have made purchases of more than $80.
SELECT * FROM Users;
SELECT * FROM Products;
SELECT * FROM Orders;
SELECT * FROM OrderDetails;

SELECT a.user_id,a.name,b.total_amount
FROM Users a
JOIN Orders b
ON a.user_id =b.user_id 
WHERE b.total_amount > 80;

-- 2. Retrieve all orders placed in the last 280 days along with the customer name and email.
SELECT a.user_id,a.name,a.email
FROM Users a
JOIN Orders b
ON a.user_id =b.user_id 
WHERE b.order_date between '2024-05-01' and '2025-02-10' ;

-- 3. Find the average product price for each category.

SELECT category, avg(price)
FROM Products
GROUP BY category;

-- 4. List all customers who have purchased a product from the category Electronics.

SELECT distinct a.name, d.category
FROM Users a
JOIN Orders b
ON a.user_id = b.user_id
JOIN OrderDetails c
ON b.order_id = c.order_id
JOIN Products d
ON c.product_id = d.product_id
WHERE d.category = 'Electronics';

-- 5. Find the total number of products sold and the total revenue generated for each product.
SELECT b.name, sum(a.quantity),sum(a.quantity*b.price)
FROM OrderDetails a
JOIN Products  b
ON a.product_id = b.product_id
GROUP BY b.product_id;

-- 6. Update the price of all products in the Books category, increasing it by 10%.
SET SQL_SAFE_UPDATES = 0;
UPDATE Products
SET price =  (price*0.1)+price 
WHERE category = 'Books';

-- 7. Remove all orders that were placed before 2020.
DELETE FROM Orders
WHERE order_date < '2020-01-01';

-- 8. Write a query to fetch the order details, including customer name, product name, and quantity, for orders placed on 2024-05-01.
SELECT b.order_id,a.name,d.name,c.quantity
FROM Users a
JOIN Orders b
ON a.user_id = b.user_id
JOIN OrderDetails c
ON b.order_id = c.order_id
JOIN Products d
ON c.product_id = d.product_id
WHERE b.order_date = '2024-05-01';

-- 9. Fetch all customers and the total number of orders they have placed.

SELECT a.name, count(b.order_id)
FROM Users a
LEFT JOIN Orders b
ON a.user_id = b.user_id
GROUP BY a.user_id;

-- 10. Retrieve the average rating for all products in the Electronics category.
SELECT name, avg(price)
FROM Products
WHERE category = 'Electronics'
GROUP BY name;

-- 11.List all customers who purchased more than 1 units of any product, including the product name and total quantity purchased.

SELECT  a.name, c.product_id,d.name,sum(c.quantity) as total_quantity
FROM Users a
LEFT JOIN Orders b
ON a.user_id = b.user_id
JOIN OrderDetails c
ON b.order_id = c.order_id
JOIN Products d
ON c.product_id = d.product_id
GROUP BY a.name,c.product_id
HAVING total_quantity>1;

-- 12. Find the total revenue generated by each category along with the category name.

SELECT b.category,sum(a.quantity*b.price) as total_revenue
FROM OrderDetails a
JOIN Products  b
ON a.product_id = b.product_id
GROUP BY b.category;

